import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | Snow Day Predictor Protocol',
  description: 'Legal disclaimers, liability limitations, and affiliate disclosures for the Snow Day Predictor.',
};

export default function TermsPage() {
  return (
    <div className="bg-slate-950 min-h-screen text-slate-300 py-12 px-6 font-sans selection:bg-cyan-400 selection:text-slate-900">
      
      {/* --- NAVIGATION --- */}
      <div className="max-w-4xl mx-auto mb-8">
        <Link href="/" className="text-cyan-400 text-xs font-black uppercase tracking-widest hover:text-white transition-colors flex items-center gap-2 group">
            <span className="group-hover:-translate-x-1 transition-transform">←</span> Return to Intel Hub
        </Link>
      </div>

      <div className="max-w-4xl mx-auto bg-slate-900 p-8 md:p-12 rounded-[2rem] border border-slate-800 shadow-2xl relative overflow-hidden">
        
        {/* Background Watermark */}
        <div className="absolute top-0 right-0 p-12 opacity-5 text-9xl pointer-events-none select-none">⚖️</div>

        {/* Header */}
        <div className="border-b border-slate-800 pb-8 mb-8">
            <h1 className="text-3xl md:text-5xl font-black text-white mb-4 uppercase italic tracking-tighter">
                Terms of Service
            </h1>
            <div className="flex flex-col md:flex-row gap-4 items-start md:items-center">
                <span className="bg-cyan-950 text-cyan-400 text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded border border-cyan-900">
                    Protocol: V-2026.1
                </span>
                <p className="text-slate-500 font-bold uppercase tracking-wider text-xs">
                    AKA: "Don't Sue Us If You Fail Your Math Test"
                </p>
            </div>
        </div>

        <div className="space-y-12 text-sm md:text-base leading-relaxed text-slate-300">
          
          {/* Section 1 */}
          <section>
              <h3 className="text-xl font-black text-white mb-4 uppercase flex items-center gap-3">
                  <span className="text-cyan-500">01 //</span> Acceptance of Terms
              </h3>
              <p>
                By accessing <strong>School Snow Day Predictor</strong> ("the Site"), you agree to these Terms of Service. 
                If you do not agree to these terms, please close this browser tab immediately and proceed to do your homework. 
                Continued use of the site constitutes your agreement to be bound by these protocols.
              </p>
          </section>

          {/* Section 2 - The Big Disclaimer */}
          <section className="bg-red-950/20 border-l-4 border-red-500 p-6 rounded-r-xl">
              <h3 className="text-xl font-black text-red-500 mb-4 uppercase flex items-center gap-3">
                  02 // Entertainment Purposes Only
              </h3>
              <p className="mb-4 text-white font-bold">
                THIS IS CRITICAL: WE ARE NOT THE SCHOOL BOARD.
              </p>
              <p className="mb-4">
                This website is a prediction tool powered by meteorological algorithms and historical data analysis. 
                We do <strong>not</strong> have the authority to cancel school, buses, exams, or field trips.
              </p>
              <p>
                Any "Probability," "Odds," or "Predictions" generated by this site are estimates only. 
                You should <strong>ALWAYS</strong> verify official school status with your specific School Board website (TDSB, YRDSB, PDSB, etc.) or local news station before deciding to sleep in.
              </p>
          </section>

          {/* Section 3 */}
          <section>
              <h3 className="text-xl font-black text-white mb-4 uppercase flex items-center gap-3">
                  <span className="text-cyan-500">03 //</span> Limitation of Liability
              </h3>
              <p className="mb-4">
                To the fullest extent permitted by applicable law, School Snow Day Predictor and its operators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your use of this site, including but not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-slate-400 marker:text-cyan-500">
                <li>Any missed exams, classes, assignments, or bus pickups resulting from reliance on our data.</li>
                <li>Any physical injury (frostbite, slips, falls) incurred because you relied on our wind chill data rather than looking outside.</li>
                <li>Any emotional distress caused by a "99% Chance" prediction that resulted in a regular school day (we feel your pain, but we are not liable for it).</li>
              </ul>
          </section>

          {/* Section 4 - Affiliate Disclosure (Amazon Requirement) */}
          <section className="bg-slate-950 p-6 rounded-xl border border-slate-800">
              <h3 className="text-xl font-black text-white mb-4 uppercase flex items-center gap-3">
                  <span className="text-cyan-500">04 //</span> Affiliate Disclosure
              </h3>
              <p className="mb-4">
                Transparency is key. We participate in the <strong>Amazon Services LLC Associates Program</strong>, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.ca and Amazon.com.
              </p>
              <p>
                This means that some links on this site (specifically those recommending winter gear, sleds, or emergency kits) are "affiliate links." 
                If you click on these links and make a purchase, we may earn a small commission at <strong>no extra cost to you</strong>. This helps keep our servers running and our radar data live.
              </p>
          </section>

          {/* Section 5 */}
          <section>
              <h3 className="text-xl font-black text-white mb-4 uppercase flex items-center gap-3">
                  <span className="text-cyan-500">05 //</span> Intellectual Property
              </h3>
              <p>
                The "Snow Day Algorithm," the specific weighting of "Diesel Gel Points," and the "Pajama Index" methodology are proprietary concepts of this site. 
                You may share our predictions on social media (please do!), but you may not scrape our data or reproduce our calculator code without permission.
              </p>
          </section>

          {/* Section 6 */}
          <section>
              <h3 className="text-xl font-black text-white mb-4 uppercase flex items-center gap-3">
                  <span className="text-cyan-500">06 //</span> Contact & Governance
              </h3>
              <p className="mb-4">
                These terms are governed by the laws of <strong>Ontario, Canada</strong>. Any disputes arising from these terms shall be resolved in the courts of Ontario.
              </p>
              <p>
                <strong>Questions? Found a bug?</strong><br/>
                Contact the Command Center at: <span className="text-cyan-400 font-mono bg-cyan-950/30 px-2 py-1 rounded">mliselectpro@gmail.com</span>
              </p>
          </section>

          {/* Footer Timestamp */}
          <div className="border-t border-slate-800 pt-8 mt-12 text-center text-xs text-slate-600 uppercase tracking-widest font-bold">
            Last Updated: January 26, 2026 // Status: Active
          </div>

        </div>
      </div>
    </div>
  );
}
