export default function TermsPage() {
  return (
    <div className="bg-slate-900 min-h-screen text-slate-300 py-12 px-6 font-sans">
      <div className="max-w-3xl mx-auto bg-slate-800 p-8 rounded-xl border border-slate-700 shadow-2xl">
        <h1 className="text-3xl font-black text-white mb-2">Terms of Service</h1>
        <p className="text-cyan-400 font-bold mb-8 uppercase tracking-wider text-sm">
          AKA: "Don't Sue Us If You Fail Your Math Test"
        </p>

        <div className="space-y-6 text-sm leading-relaxed">
          <p>
            <strong>Last Updated:</strong> January 26, 2026.
          </p>

          <h3 className="text-xl font-bold text-white mt-8">1. Acceptance of Terms</h3>
          <p>
            By accessing School Snow Day Predictor ("the Site"), you agree to these Terms. 
            If you do not agree, please close the tab and go do your homework.
          </p>

          <h3 className="text-xl font-bold text-white mt-8">2. For Entertainment Purposes Only</h3>
          <p className="uppercase font-bold text-red-400">
            THIS IS IMPORTANT:
          </p>
          <p>
            This website is a prediction tool based on weather algorithms. 
            <strong>WE ARE NOT THE SCHOOL BOARD.</strong> 
            We do not have the authority to cancel school, buses, or exams. 
            Any "predictions" or "odds" generated by this site are estimates only.
          </p>
          <p>
            You should <strong>ALWAYS</strong> verify school status with your official school board website or local news station before deciding to sleep in.
          </p>

          <h3 className="text-xl font-bold text-white mt-8">3. Limitation of Liability</h3>
          <p>
            To the fullest extent permitted by law, School Snow Day Predictor shall not be liable for:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>Any missed exams, classes, or bus pickups resulting from reliance on our data.</li>
            <li>Any frostbite incurred because you thought it was "warm enough" based on our wind chill data.</li>
            <li>Any emotional distress caused by a "99% Chance" that turned into a regular school day.</li>
          </ul>

          <h3 className="text-xl font-bold text-white mt-8">4. Affiliate Links</h3>
          <p>
            We participate in the Amazon Services LLC Associates Program. 
            Some links on this site are "affiliate links," meaning we may earn a commission if you purchase items (like sleds or cocoa) through them.
          </p>

          <h3 className="text-xl font-bold text-white mt-8">5. Changes to Terms</h3>
          <p>
            We reserve the right to change these terms at any time. We usually won't, but we can.
          </p>

          <h3 className="text-xl font-bold text-white mt-8">6. Contact</h3>
          <p>
            Questions? Email us at <span className="text-white font-mono">mliselectpro@gmail.com</span>.
          </p>
        </div>
      </div>
    </div>
  );
}
