import Link from 'next/link';

export const metadata = {
  title: 'Wednesday Verdict | School Snow Day Predictor',
  description: 'Breaking down the plying saturation and freezing conditions for January 28.',
};

export default function WednesdayVerdict() {
  return (
    <div style={{ backgroundColor: '#ffffff', color: '#333333', minHeight: '100vh', fontFamily: 'sans-serif', padding: '40px 20px' }}>
      
      <main style={{ maxWidth: '700px', margin: '0 auto' }}>
        
        {/* BACK LINK */}
        <div style={{ marginBottom: '20px' }}>
          <Link href="/" style={{ color: '#0070f3', textDecoration: 'none', fontSize: '1rem' }}>
            ← Back to Predictor
          </Link>
        </div>

        {/* TITLE SECTION */}
        <header style={{ marginBottom: '40px' }}>
          <h1 style={{ fontSize: '2.5rem', fontWeight: '800', marginBottom: '10px', lineHeight: '1.2', color: '#000' }}>
            Wednesday Verdict: Plowing Saturation & The Diesel Gel Point
          </h1>
          <p style={{ fontSize: '1.2rem', color: '#666', lineHeight: '1.5' }}>
            Analyzing why the "Snowbelt" is at critical risk while the GTA faces a different kind of morning threat.
          </p>
        </header>

        {/* CONTENT SECTION */}
        <article style={{ fontSize: '1.1rem', lineHeight: '1.7', color: '#333' }}>
          <p style={{ marginBottom: '20px' }}>
            As we approach the morning of January 28, the forecast has shifted from a general "snow event" to a high-stakes logistical battle. While the total accumulation in Toronto remains manageable, the regions to the north are hitting a breaking point.
          </p>

          <h3 style={{ fontSize: '1.5rem', fontWeight: '700', marginTop: '30px', marginBottom: '15px' }}>
            1. The "Infrastructure Saturation" Limit
          </h3>
          <p style={{ marginBottom: '20px' }}>
            In Simcoe and Grey-Bruce, municipal plows have been running for 48 hours straight. We are tracking "Infrastructure Saturation"—the point where residential side streets can no longer be cleared faster than the lake-effect squalls fill them back in. For bus operators, this is an automatic "No-Go."
          </p>

          <h3 style={{ fontSize: '1.5rem', fontWeight: '700', marginTop: '30px', marginBottom: '15px' }}>
            2. The Diesel Gel Point
          </h3>
          <p style={{ marginBottom: '20px' }}>
            Tonight’s temperatures are dipping into the "Danger Zone" for rural bus fleets. When temperatures drop below -20°C, untreated diesel can begin to "gel," causing fuel filters to clog. Even if the roads are plowed, a fleet that won't start is a fleet that can't pick up students.
          </p>

          <h3 style={{ fontSize: '1.5rem', fontWeight: '700', marginTop: '30px', marginBottom: '15px' }}>
            3. The GTA "Black Ice" Factor
          </h3>
          <p style={{ marginBottom: '20px' }}>
            For the TDSB, YRDSB, and PDSB, the snow is less of a factor than the flash freeze. Any slush remaining from today will be solid ice by 5:00 AM. While schools usually stay open for walkers, we expect significant delays for any bused routes.
          </p>

          {/* BOXED PREDICTION */}
          <div style={{ marginTop: '40px', padding: '25px', backgroundColor: '#f0f7ff', borderLeft: '5px solid #0070f3', borderRadius: '4px' }}>
            <h4 style={{ margin: '0 0 10px 0', fontSize: '1.2rem', color: '#0070f3' }}>Current Wednesday Prediction:</h4>
            <p style={{ margin: '0', fontSize: '1.3rem', fontWeight: 'bold' }}>
              Snowbelt: 95% Bus Cancellation<br />
              GTA: 15% Bus Cancellation / 85% Delay Risk
            </p>
          </div>
        </article>

        {/* FOOTER */}
        <footer style={{ marginTop: '60px', borderTop: '1px solid #eee', paddingTop: '20px', textAlign: 'center' }}>
          <p style={{ fontSize: '0.8rem', color: '#999' }}>
            Analysis generated by the Intelligence Hub Data Engine. Verified against regional transit and meteorological sensors.
          </p>
        </footer>
      </main>
    </div>
  );
}
