import Head from 'next/head';
import Link from 'next/link';

export default function WednesdayVerdict() {
  const date = "Wednesday, January 28, 2026";
  
  return (
    <div style={{ backgroundColor: '#0a0a0a', color: '#e0e0e0', minHeight: '100vh', fontFamily: 'monospace', padding: '20px' }}>
      <Head>
        <title>Wednesday Verdict | Snow Day Intelligence Hub</title>
        <meta name="description" content={`Tactical snow day predictions for ${date}`} />
      </Head>

      <main style={{ maxWidth: '800px', margin: '0 auto', border: '1px solid #333', padding: '30px', borderRadius: '8px', backgroundColor: '#111' }}>
        
        {/* HEADER */}
        <header style={{ borderBottom: '2px solid #ff4d4d', marginBottom: '20px', paddingBottom: '10px' }}>
          <h1 style={{ color: '#ff4d4d', fontSize: '1.5rem', margin: '0' }}>📡 TACTICAL DOSSIER: JAN 28 VERDICT</h1>
          <p style={{ fontSize: '0.9rem', color: '#888' }}>FILE ID: ON-SQUALL-2026-028 | STATUS: ACTIVE</p>
        </header>

        {/* SUMMARY SECTION */}
        <section style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#fff', fontSize: '1.2rem' }}>🛰️ REGIONAL SCAN SUMMARY</h2>
          <p>
            Current satellite imagery confirms a **Double-Threat** setup for Wednesday morning. 
            While the GTA remains in a deep freeze, the **Snowbelt (Simcoe/Grey-Bruce)** is facing 
            Infrastructure Saturation from persistent lake-effect bands.
          </p>
        </section>

        {/* THE RISK GRID */}
        <div style={{ display: 'grid', gap: '15px', marginBottom: '30px' }}>
          <div style={{ padding: '15px', borderLeft: '4px solid #ff4d4d', backgroundColor: '#1a1a1a' }}>
            <h3 style={{ margin: '0', color: '#ff4d4d' }}>🔴 SNOWBELT: 90% RISK</h3>
            <p style={{ fontSize: '0.9rem' }}>Grey-Bruce, Simcoe County. Plowing saturation has reached critical limits. Rural bus routes are likely compromised by 'Snow Ramping' on overpasses.</p>
          </div>

          <div style={{ padding: '15px', borderLeft: '4px solid #ffcc00', backgroundColor: '#1a1a1a' }}>
            <h3 style={{ margin: '0', color: '#ffcc00' }}>🟡 GTA CORRIDOR: 15% RISK</h3>
            <p style={{ fontSize: '0.9rem' }}>TDSB/YRDSB/PDSB. Low snowfall totals, but **Black Ice** signatures are at an 8.5/10 risk. Expect 'Code Cold' delays rather than cancellations.</p>
          </div>
        </div>

        {/* TECHNICAL INTEL */}
        <section style={{ padding: '20px', backgroundColor: '#000', border: '1px dashed #444', marginBottom: '30px' }}>
          <h3 style={{ color: '#00ff00', fontSize: '1rem', marginTop: '0' }}>📟 TECHNICAL SENSOR DATA</h3>
          <ul style={{ listStyleType: 'none', padding: '0', fontSize: '0.85rem', lineHeight: '1.8' }}>
            <li>- **DIESEL GEL POINT:** 7.5/10 (High Risk for engine failure in rural fleets)</li>
            <li>- **VISIBILITY RATING:** 2/10 (Near-zero in Georgian Bay squall bands)</li>
            <li>- **ICE ACCRETION:** High Probability on Highway 400 overpasses.</li>
          </ul>
        </section>

        {/* CTA */}
        <footer style={{ textAlign: 'center', marginTop: '40px' }}>
          <Link href="/" style={{ color: '#ff4d4d', textDecoration: 'none', border: '1px solid #ff4d4d', padding: '10px 20px', borderRadius: '4px' }}>
            RETURN TO LIVE SCANNER
          </Link>
          <p style={{ fontSize: '0.7rem', color: '#666', marginTop: '20px' }}>
            Disclaimer: Analysis generated by the Intelligence Hub Data Engine. Verified against regional transit and meteorological sensors.
          </p>
        </footer>
      </main>
    </div>
  );
}
